theme: jekyll-theme-minimal
title: Daniel Fernandez
email: <p style="color:black" "font-family:lucida console">dtrade84@outlook.com</p>
logo: logo.jpg

description: 
    Data Scientist <br>
    Service Management Specialist <br>
    Memorial healthcare System <br>              
    Gainesville, FL <br> 
    Bs Data Management / Data Analysis <br>
    Western Governors University <br> 
plugins:
   - jekyll-sitemap
   - jekyll-seo-tag
   - jemoji
   
# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
sidebar:
   - name: GitHub
     icon: <i class="fa-regular fa-user"></i>
     link: https://github.com/dtrade84
   - name: Project Repository
     icon: <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" style="vertical-align:-0.125em;" width="1em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 16 16"><g fill="currentColor"><path d="M12.643 15C13.979 15 15 13.845 15 12.5V5H1v7.5C1 13.845 2.021 15 3.357 15h9.286zM5.5 7h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1 0-1zM.8 1a.8.8 0 0 0-.8.8V3a.8.8 0 0 0 .8.8h14.4A.8.8 0 0 0 16 3V1.8a.8.8 0 0 0-.8-.8H.8z"/></g></svg>
     link: https://github.com/BDHU/minimalist

google_analytics: UA-236999281-1


